AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  KMSKey:
    Type: String
  RedisEndpoint:
    Type: String
  RedisPort:
    Type: String

Resources:
  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${Environment}/database'
      Description: 'Credenciais e configurações do banco de dados'
      SecretString: !Sub |
        {
          "redis_endpoint": "${RedisEndpoint}",
          "redis_port": "${RedisEndpoint}",
          "kms_key_id": "${KMSKey}",
          "environment": "${Environment}"
        }
      KmsKeyId: !Ref KMSKey
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-database-secret'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  DatabaseSecret:
    Value: !Ref DatabaseSecret
